version: "3.1"

services:
  pg:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 8080:5432
  redis:
    image: redis
    restart: always
    ports:
      - 8081:6379
    volumes:
      - ./tmp/redis:/data
