# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: pg-dev
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: <%= ENV.fetch("DB_USER_NAME") { "admin" } %>
  password: <%= ENV.fetch("DB_USER_PASSWORD") { "admin" } %>

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: admin
  password: admin