default: &default
  timeout: 10000
  adapter: postgresql
  encoding: unicode
  host: pg
  # port: 8080
  pool: 10
  username: postgres
  password: example

development:
  <<: *default
  database: ssl-monitor_db_d

production:
  <<: *default
  database: ssl-monitor_db_p

test:
  <<: *default
  database: ssl-monitor_db_t